# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IPA
                                 A QGIS plugin
 This plugin analysis InSAR products.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-20
        copyright            : (C) 2024 by Fabio Piccolino
        email                : f.piccolino@studenti.poliba.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IPA class from file IPA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .IPA import IPA
    return IPA(iface)
